# Pulumi Azure Pipelines task extension
# Run tests and create a new artifact
# to be published in the Visual Studio Marketplace
# under the pulumi publisher ID.

trigger:
- master

stages:
- stage: build
  displayName: 'Build and test'
  jobs:
  - job: build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'Restore node_modules for buildAndReleaseTask/'
      inputs:
        workingDir: buildAndReleaseTask/
        verbose: true

    - task: Npm@1
      displayName: 'Restore node_modules for buildAndReleaseTask/tests/'
      inputs:
        workingDir: buildAndReleaseTask/tests
        verbose: true

    - task: Npm@1
      displayName: 'Run unit tests'
      inputs:
        command: 'custom'
        customCommand: run test
      env:
        INPUT_AZURESUBSCRIPTION: 'fake-subscription-id'

- stage: package
  condition:
    or(
      eq(variables['Build.Reason'], 'IndividualCI'),
      eq(variables['Build.Reason'], 'BatchedCI'),
      eq(variables['ManualOverride'], 'true')
    )
  displayName: 'Package extension'
  jobs:
  - job: restoreDeps
    displayName: 'Restore dependencies'
    steps:
    - task: Npm@1
      displayName: 'Restore node_modules for buildAndReleaseTask/'
      inputs:
        workingDir: buildAndReleaseTask/
        verbose: true

    - task: Npm@1
      displayName: 'Compile TS to JS'
      inputs:
        workingDir: buildAndReleaseTask/
        command: 'custom'
        customCommand: run tsc

  - job: tfxCreate
    displayName: 'Create and package VSIX'
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: QueryAzureDevOpsExtensionVersion@2
      displayName: 'Query extension version'
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Pulumi Marketplace'
        publisherId: 'pulumi'
        extensionId: 'build-and-release-task'
        versionAction: 'Patch'
        extensionVersionOverride: 'Extension.VersionOverride'

    - task: PackageAzureDevOpsExtension@2
      displayName: 'Package extension'
      inputs:
        extensionVersion: '$(Extension.Version)'
        updateTasksVersion: true
        updateTasksVersionType: patch

    - task: PublishPipelineArtifact@0
      displayName: 'Create pipeline artifact'
      inputs:
        artifactName: 'vsix'
        targetPath: $(Extension.OutputPath)

  - job: testTfxCreate
    displayName: 'Create and publish test VSIX'
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: CmdLine@2
      displayName: 'Update task name'
      inputs:
        script: 'sed -i ''s/"Pulumi"/"Test Pulumi"/g'' task.json'
        workingDirectory: './buildAndReleaseTask/'
        failOnStderr: true

    - task: CmdLine@2
      displayName: 'Update task id'
      inputs:
        script: 'sed -i ''s/"66148448-e174-4167-91a4-0ac63f4a10ca"/"f7c2cffd-7ad2-4db6-b699-205f9e99837c"/g'' task.json'
        workingDirectory: './buildAndReleaseTask/'
        failOnStderr: true

    - task: QueryAzureDevOpsExtensionVersion@2
      displayName: 'Query extension version'
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Pulumi Marketplace'
        publisherId: 'pulumi'
        extensionId: 'build-and-release-task'
        versionAction: 'Patch'

    - task: PublishAzureDevOpsExtension@2
      displayName: 'Package and publish test VSIX'
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Pulumi Marketplace'
        fileType: 'manifest'
        publisherId: 'pulumi'
        extensionId: 'test-build-and-release-task'
        extensionName: '(Test) Pulumi Azure Pipelines Task'
        extensionVersion: '$(Extension.Version)'
        extensionVisibility: 'private'
        extensionPricing: 'free'
        shareWith: 'pulumi'
